const express = require('express')
const app = express()
app.use(express.static('public'))
app.set('view engine', 'pug')
app.get('/register', (req, res) => res.sendfile("register.html"))
app.get('/profile', (req, res) => res.sendfile("profile.html"))
app.get('/login', (req, res) => res.sendfile("login.html"))
app.get('/canvas', (req, res) => res.sendfile("canvas.html"))
app.get('/gallery', (req, res) => res.render("gallery"))
app.get('/', (req, res) => res.sendfile("pixel.html"))
app.listen(3000, () => console.log('Example app listening on port 3000!'))